name: Cleanup Docker
description: 'Clean up unused Docker images and resources via SSH'

inputs:
  cleanup_mode:
    description: 'Cleanup mode: dangling (just dangling images), images (all unused images), full (images + containers + volumes)'
    required: false
    default: 'images'
  ts_oauth_client_id:
    description: 'Tailscale OAuth client ID'
    required: true
  ts_oauth_secret:
    description: 'Tailscale OAuth client secret'
    required: true
  ssh_private_key:
    description: 'SSH private key'
    required: true
  ssh_user:
    description: 'SSH username'
    required: true

runs:
  using: composite
  steps:
    - name: Connect to Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ inputs.ts_oauth_client_id }}
        oauth-secret: ${{ inputs.ts_oauth_secret }}
        tags: tag:ci
        version: latest

    - name: Cleanup Docker Resources
      uses: appleboy/ssh-action@v1
      with:
        host: homelab
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_private_key }}
        script: |
          echo "🧹 Starting Docker cleanup (mode: ${{ inputs.cleanup_mode }})"
          
          case "${{ inputs.cleanup_mode }}" in
            dangling)
              echo "Removing dangling images only..."
              docker image prune -f
              ;;
            images)
              echo "Removing all unused images..."
              docker image prune -a -f
              ;;
            full)
              echo "Removing unused images, containers, and volumes..."
              docker system prune -a -f --volumes
              ;;
            *)
              echo "Unknown cleanup mode: ${{ inputs.cleanup_mode }}"
              exit 1
              ;;
          esac
          
          echo "✅ Cleanup complete"
          echo ""
          echo "📊 Current disk usage:"
          docker system df
