name: Deploy Service
description: 'Deploy a Docker Compose service via SSH over Tailscale'

inputs:
  service_name:
    description: 'Name of the service to deploy'
    required: true
  service_path:
    description: 'Path to the service directory'
    required: true
  deploy_script:
    description: 'Custom deployment script'
    required: false
    default: ./start.sh
  repo_dir:
    description: 'Absolute path to the homelab repo on the server'
    required: false
    default: /home/mircea/homeserver
  ts_oauth_client_id:
    description: 'Tailscale OAuth client ID'
    required: true
  ts_oauth_secret:
    description: 'Tailscale OAuth client secret'
    required: true
  ssh_private_key:
    description: 'SSH private key'
    required: true
  ssh_user:
    description: 'SSH username'
    required: true
  ssh_host:
    description: 'SSH host for the homelab server'
    required: false
    default: homelab

runs:
  using: composite
  steps:
    - name: Connect to Tailscale
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: ${{ inputs.ts_oauth_client_id }}
        oauth-secret: ${{ inputs.ts_oauth_secret }}
        tags: tag:ci
        version: latest

    - name: Deploy ${{ inputs.service_name }}
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_private_key }}
        timeout: 30m
        command_timeout: 25m
        script_stop: true
        script: |
          set -euo pipefail
          if [ ! -d "${{ inputs.repo_dir }}" ]; then
            echo "Repo dir not found: ${{ inputs.repo_dir }}"
            exit 1
          fi
          cd ${{ inputs.repo_dir }}
          git fetch --prune
          git checkout main
          git pull --ff-only
          cd ${{ inputs.service_path }}
          ${{ inputs.deploy_script }} --quiet 2>&1 | tail -20
